function ctrl = Vulintus_OTSC_Cage_Light_Functions(ctrl, otsc_codes, varargin)

%Vulintus_OTSC_Cage_Light_Functions.m - Vulintus, Inc., 2024
%
%   VULINTUS_OTSC_CAGE_LIGHT_FUNCTIONS defines and adds OmniTrak Serial
%   Communication (OTSC) functions to the control structure for Vulintus
%   OmniTrak devices which can control overhead cage lights.
% 
%   NOTE: These functions are designed to be used with the "serialport" 
%   object introduced in MATLAB R2019b and will not work with the older 
%   "serial" object communication.
%
%   UPDATE LOG:
%   2024-04-23 - Drew Sloan - Function first created.
%   2024-06-07 - Drew Sloan - Added a optional "devices" input argument to
%                             selectively add the functions to the control 
%                             structure.
%


%List the Vulintus devices that use these functions.
device_list = { 'OT-3P',...
                'OT-CC'};

%If an cell arracy of connected devices was provided, match against the device lis.
if nargin > 2
    connected_devices = varargin{1};                                        %Grab the list of connected devices.
    [~,i,~] = intersect(connected_devices,device_list);                     %Look for any matches between the two device lists.
    if ~any(i)                                                              %If no match was found...
        if isfield(ctrl,'light')                                            %If there's a "light" field in the control structure...
            ctrl = rmfield(ctrl,'light');                                   %Remove it.
        end
        return                                                              %Skip execution of the rest of the function.
    end
end

serialcon = ctrl.serialcon;                                                 %Grab the handle for the serial connection.

%Overhead cage light functions.
ctrl.light = [];                                                            %Create a field to hold overhead cage light functions.

%Turn on/off the overhead cage light.
ctrl.light.on = ...
    @(varargin)Vulintus_OTSC_Transaction(serialcon,...
    otsc_codes.CAGE_LIGHT_ON,...
    varargin{:});                                  
ctrl.light.off = ...
    @(varargin)Vulintus_OTSC_Transaction(serialcon,...
    otsc_codes.CAGE_LIGHT_OFF,...
    varargin{:});

%Request/set the RGBW values for the overhead cage light (0-255).
ctrl.light.rgbw.get = ...
    @(varargin)Vulintus_OTSC_Transaction(serialcon,...
    otsc_codes.REQ_CAGE_LIGHT_RGBW,...
    'reply',{4,'uint8'},...
    varargin{:});               
ctrl.light.rgbw.set = ...
    @(rgbw,varargin)Vulintus_OTSC_Transaction(serialcon,...
    otsc_codes.CAGE_LIGHT_RGBW,...
    'data',{rgbw,'uint8'},...
    varargin{:});

%Request/set the overhead cage light duration, in milliseconds.
ctrl.light.dur.get = ...
    @(varargin)Vulintus_OTSC_Transaction(serialcon,...
    otsc_codes.REQ_CAGE_LIGHT_DUR,...
    'reply',{1,'uint16'},...
    varargin{:});           
ctrl.light.dur.set = ...
    @(dur,varargin)Vulintus_OTSC_Transaction(serialcon,...
    otsc_codes.CAGE_LIGHT_DUR,...
    'data',{dur,'uint16'},...
    varargin{:});

    