function Vulintus_Show_Error_Report(program, err)

%
%Vulintus_Show_Error_Report.m - Vulintus, Inc.
%
%   Vulintus_Show_Error_Report creates a pop-up summary of an error report,
%   which is useful when programs are compiled and running without a
%   command line display. The functon blocks execution until the summary is
%   closed.
%   
%   UPDATE LOG:
%   11/19/2019 - Drew Sloan - Function first created, adapted from
%       Vulintus_Send_Error_Report.m.
%

fig = figure('menubar','none',...
    'name',upper([program ' Error Summary']),...
    'numbertitle','off');
ax = axes('units','normalized',...
    'position',[0 0 1 1],...
    'color','w',...
    'xlim',[0,1],...
    'ylim',[0,1],...
    'parent',fig);
t = text(0.05,1,err.identifier,...
    'fontsize',10,...
    'horizontalalignment','left',...
    'verticalalignment','top',...
    'interpreter','none',...
    'parent',ax);
y = get(t,'extent');
t = text(0.05,y(2) - 0.01,['     ' err.message],...
    'fontsize',10,...
    'horizontalalignment','left',...
    'verticalalignment','top',...
    'interpreter','none',...
    'parent',ax);
for i = 1:length(err.stack)
    y = get(t,'extent');
    t = text(0.05,y(2) - 0.01,err.stack(i).name,...
        'fontsize',10,...
        'horizontalalignment','left',...
        'verticalalignment','top',...
        'interpreter','none',...
        'parent',ax);
    y = get(t,'extent');
    t = text(0.05,y(2) - 0.01,['     LINE: ' num2str(err.stack(i).line)],...
        'fontsize',10,...
        'horizontalalignment','left',...
        'verticalalignment','top',...
        'interpreter','none',...
        'parent',ax);
end
set(ax,'xtick',[],'ytick',[]);
uiwait(fig);