function Vibrotactile_Detection_Create_Session_Plots(behavior)

%
% Vibrotactile_Detection_Create_Session_Plots.m
%
%   copyright 2024, Vulintus, Inc.
%
%   VIBROTACTILE_DETECTION_CREATE_SESSION_PLOTS initializes all of the GUI 
%   plots at the start of a behavioral session for the SensiTrak 
%   vibrotactile detection task
%   
%   UPDATE LOG:
%   2024-11-13 - Drew Sloan - Function first implemented, adapted from
%                             "Vibrotactile_Detection_Task_Create_Session_Plots.m".
%


cla(behavior.ui.ax.data);                                                   %Clear the data axes.
hold(behavior.ui.ax.data,'on');                                             %Hold the axes for multiple plots.
% behavior.session.display.trial.plot = ...
%     area([0,behavior.session.params.trial_dur],[0,0],...
%     'facecolor',[0 0.5 0],...
%     'visible','off',...
%     'parent',behavior.ui.ax.data);                                          %Plot a dummy line in place of the trial plot.
% line([0,behavior.session.params.trial_dur],[0,0],...
%     'color','k',...
%     'parent',behavior.ui.ax.data);                                          %Plot a line across the x-axis.
% a = ceil(behavior.session.params.trial_dur/10);                             %Find spacing for approximately 10 ticks along the x-axis.
% for i = 0:a:behavior.session.params.trial_dur                               %Step through the x-axis ticks.
%     line([i,i],[-0.05,0.05],...
%         'color','k',...
%         'parent',behavior.ui.ax.data);                                      %Draw tick lines on the x-axis.
%     text(i,-0.05,num2str(i),...
%         'horizontalalignment','center',...
%         'verticalalignment','top',...
%         'fontsize',8,...
%         'parent',behavior.ui.ax.data);                                      %Label each tick line.
% end
% behavior.session.display.trial.y_axis = line([0,0],[0,1.05],...
%     'color','k',...
%     'parent',behavior.ui.ax.data);                                          %Plot a line across the y-axis.
% behavior.session.display.trial.yscale = behavior.session.params.force_thresh;     %Set the default y-scale to the hit threshold.
% a = ceil(behavior.session.display.trial.yscale/5);                          %Find spacing for approximately 10 ticks along the x-axis.
% for i = 0:a:behavior.session.display.trial.yscale                           %Step through the y-axis ticks.
%     line([-0.02,0.02]*behavior.session.params.trial_dur,...
%         [i,i]/behavior.session.display.trial.yscale,...
%         'color','k',...
%         'parent',behavior.ui.ax.data);                                      %Draw tick lines on the x-axis.
%     text(-0.03*behavior.session.params.trial_dur,...
%         i/behavior.session.display.trial.yscale,num2str(i),...
%         'horizontalalignment','right',...
%         'verticalalignment','middle',...
%         'fontsize',8,...
%         'parent',behavior.ui.ax.data);                                      %Label each tick line.
% end
% line([0,behavior.session.params.trial_dur],[1,1],...
%     'color','k',...
%     'linestyle',':',...
%     'parent',behavior.ui.ax.data);                                          %Plot a line at the threshold.
% text(0,1,'Threshold',...
%     'fontsize',8,...
%     'verticalalignment','top',...
%     'horizontalalignment','left',...
%     'parent',behavior.ui.ax.data);                                          %Create text to label the threshold.
% behavior.ui.ax.data.XLim = [-0.08,1.02]*behavior.session.params.trial_dur;  %Set the x-axis limits.
% behavior.ui.ax.data.YLim = [-0.2,1.37];                                     %Set the y-axis limits.
% text(-0.08*behavior.session.params.trial_dur,0.5,'Number of Pokes',...
%     'fontsize',8,...
%     'verticalalignment','top',...
%     'horizontalalignment','center',...
%     'rotation',90,...
%     'parent',behavior.ui.ax.data);                                          %Create a label for the y-axis.
% text(0.5*behavior.session.params.trial_dur,-0.2,'Trial Time (s)',...
%     'fontsize',8,...
%     'verticalalignment','bottom',...
%     'horizontalalignment','center',...
%     'parent',behavior.ui.ax.data);                                          %Create a label for the x-axis.
% set(behavior.ui.ax.data,'xtick',[],'ytick',[]);                             %Blank out any real x- and y-ticks.
% x = mean(behavior.ui.ax.data.XLim);                                         %Grab the mean x-coordinate.
% y = behavior.ui.ax.data.YLim;                                               %Grab the y-axis limits.
% y = y(2) - 0.1*(y(2) - y(1));                                               %Set the y-coordinate.
% behavior.session.display.trial.isitext = text(x,y,' ',...
%     'horizontalalignment','center',...
%     'verticalalignment','top',...
%     'margin',5,...
%     'backgroundcolor','w',...
%     'edgecolor','k',...
%     'visible','off',...
%     'parent',behavior.ui.ax.data);                                          %Make a text label to count down inter-trial intervals.


%Touch axes.
% cla(behavior.ui.ax.data);                                                   %Clear the touch axes.
% behavior.session.display.touch.plot = ...
%     area(1:behavior.session.params.buffsize,...
%     behavior.session.params.buffer(:,3),...
%     'linewidth',2,...
%     'facecolor',[1 0.5 0.5],...
%     'basevalue', -25,...
%     'parent',behavior.ui.ax.data);                                          %Plot some dummy data to be overwritten as an areaseries plot.
% line([1,behavior.session.params.buffsize],511.5*[1,1],...
%     'color','k',...
%     'linestyle',':',...
%     'visible','off',...
%     'parent',behavior.ui.ax.data);                                          %Plot a dotted line to show the threshold.
% ylim(behavior.ui.ax.data,[-25, 1048]);                                      %Set the y-axis limits for the touch plot.

%Get rid of the tick labels on both plots.
% set(behavior.ui.ax.data,'xlim',[1,behavior.session.params.buffsize]);       %Set the x-axis limits.
% set(behavior.ui.ax.data,'xtick',[]);                                        %Get rid of the x-axis ticks.
% set(behavior.ui.ax.data,'ytickmode','auto');                                %Set the y-tick mode to auto for the both axes.
% set(behavior.ui.ax.data,'yticklabels',[]);                                  %Set the y-tick mode to auto for the both axes.